name: Test

on: [pull_request]


jobs:
  tests:
    name: Testing

    runs-on: ubuntu-latest
    container: python:3.9.2

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_DB: thenewboston
          POSTGRES_USER: thenewboston
          POSTGRES_PASSWORD: thenewboston
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4

      - name: Install
        run: make install

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          DJANGO_APPLICATION_ENVIRONMENT: test
          REDIS_HOST: redis
          POSTGRES_HOST: postgres
          POSTGRES_DB: thenewboston
          POSTGRES_USER: thenewboston
          POSTGRES_PASSWORD: thenewboston
          SECRET_KEY: somesecret
